version: '3.8'

services:
  laravel.test:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo/app
    container_name: laravel-app
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WWWUSER: "${WWWUSER}"
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
    volumes:
      - ".:/var/www/html"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - laravel_network

volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge