services:
  laravel-app:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./:/usr/share/nginx/public
    networks:
      - app_network

  mysql-app:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    ports:
      - "3307:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_todo
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
